language: python
sudo: required
python:
  - "2.7"
# before_install:
 - sudo apt-get install -qq gfortran python-numpy python-scipy python-matplotlib
virtualenv:
  system_site_packages: true
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
script:
 - python setup.py build
 - python setup.py install
 - python runtests
