package:
  name: pysces
  version: "0.9.7"

source:
  git_url: https://github.com/PySCeS/pysces.git

build:
  number: 1
  include_recipe: True

requirements:
  build:
    - python
    - setuptools
    - numpy=1.15
    - libpython
    - mingw
    - scipy
    - matplotlib
    - nose
  run:
    - python
    - setuptools
    - numpy>=1.15
    - libpython
    - mingw
    - scipy
    - matplotlib
    - nose  
    - nose
    - python-libsbml


    
about:
  home: http://pysces.sourceforge.net
  license: BSD
  licence_file: LICENSE.txt
  summary: Python Simulator for Cellular Systems

extra:
  maintainers:
   - Brett G. Olivier
