/* File: nleq2module.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Oct  2 16:07:18 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *nleq2_error;
static PyObject *nleq2_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef int(*cb_jac_in_nleq2__user__routines_typedef)(int *,int *,double *,double *,int *);
typedef int(*cb_fcn_in_nleq2__user__routines_typedef)(int *,double *,double *,int *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

/* The following subroutine was added after the f2c translation */
double d_sign(double *a, double *b)
{
  double x;
  x = (*a >= 0 ? *a : - *a);
  return( *b >= 0 ? x : -x);
}

double pow_dd(double *ap, double *bp)
{
return(pow(*ap, *bp) );
}

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"nleq2.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)


#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)


#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
        if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
        if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
            goto capi_fail;\
    }


#define pyobj_from_int1(v) (PyLong_FromLong(v))


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef F2PY_THREAD_LOCAL_DECL
#if defined(_MSC_VER)
#define F2PY_THREAD_LOCAL_DECL __declspec(thread)
#elif defined(NPY_OS_MINGW)
#define F2PY_THREAD_LOCAL_DECL __thread
#elif defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
#define F2PY_THREAD_LOCAL_DECL _Thread_local
#elif defined(__GNUC__) \
      && (__GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ >= 4)))
#define F2PY_THREAD_LOCAL_DECL __thread
#endif
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(nleq2_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = nleq2_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
create_cb_arglist(PyObject* fun, PyTupleObject* xa , const int maxnofargs,
                  const int nofoptargs, int *nofargs, PyTupleObject **args,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    Py_ssize_t tot, opt, ext, siz, i, di = 0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun)) {
        tmp_fun = fun;
        Py_INCREF(tmp_fun);
    }
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                Py_INCREF(tmp_fun);
                tot = maxnofargs;
                if (PyCFunction_Check(fun)) {
                    /* In case the function has a co_argcount (like on PyPy) */
                    di = 0;
                }
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
            Py_INCREF(tmp_fun);
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with PyCapsule call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
            Py_INCREF(tmp_fun);
        }
    }

    if (tmp_fun == NULL) {
        fprintf(stderr,
                "Call-back argument must be function|instance|instance.__call__|f2py-function "
                "but got %s.\n",
                ((fun == NULL) ? "NULL" : Py_TYPE(fun)->tp_name));
        goto capi_fail;
    }

    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount")) {
            PyObject *tmp_argcount = PyObject_GetAttrString(tmp,"co_argcount");
            Py_DECREF(tmp);
            if (tmp_argcount == NULL) {
                goto capi_fail;
            }
            tot = PyLong_AsSsize_t(tmp_argcount) - di;
            Py_DECREF(tmp_argcount);
        }
    }
    /* Get the number of optional arguments */
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);

#ifdef DEBUGCFUNCS
    fprintf(stderr,
            "debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),"
            "tot,opt,ext,siz,nofargs = %d(-%d), %zd, %zd, %zd, %zd, %d\n",
            maxnofargs, nofoptargs, tot, opt, ext, siz, *nofargs);
#endif

    if (siz < tot-opt) {
        fprintf(stderr,
                "create_cb_arglist: Failed to build argument list "
                "(siz) with enough arguments (tot-opt) required by "
                "user-supplied function (siz,tot,opt=%zd, %zd, %zd).\n",
                siz, tot, opt);
        goto capi_fail;
    }

    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    Py_DECREF(tmp_fun);
    return 1;

capi_fail:
    if (PyErr_Occurred() == NULL)
        PyErr_SetString(nleq2_error, errmess);
    Py_XDECREF(tmp_fun);
    return 0;
}


static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = nleq2_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern int F_FUNC(nleq2,NLEQ2)(int*,cb_fcn_in_nleq2__user__routines_typedef,cb_jac_in_nleq2__user__routines_typedef,double*,double*,double*,int*,int*,int*,int*,int*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/********************** cb_fcn_in_nleq2__user__routines **********************/
typedef struct {
    PyObject *capi;
    PyTupleObject *args_capi;
    int nofargs;
    jmp_buf jmpbuf;
} cb_fcn_in_nleq2__user__routines_t;

#if defined(F2PY_THREAD_LOCAL_DECL) && !defined(F2PY_USE_PYTHON_TLS)

static F2PY_THREAD_LOCAL_DECL cb_fcn_in_nleq2__user__routines_t *_active_cb_fcn_in_nleq2__user__routines = NULL;

static cb_fcn_in_nleq2__user__routines_t *swap_active_cb_fcn_in_nleq2__user__routines(cb_fcn_in_nleq2__user__routines_t *ptr) {
    cb_fcn_in_nleq2__user__routines_t *prev = _active_cb_fcn_in_nleq2__user__routines;
    _active_cb_fcn_in_nleq2__user__routines = ptr;
    return prev;
}

static cb_fcn_in_nleq2__user__routines_t *get_active_cb_fcn_in_nleq2__user__routines(void) {
    return _active_cb_fcn_in_nleq2__user__routines;
}

#else

static cb_fcn_in_nleq2__user__routines_t *swap_active_cb_fcn_in_nleq2__user__routines(cb_fcn_in_nleq2__user__routines_t *ptr) {
    char *key = "__f2py_cb_cb_fcn_in_nleq2__user__routines";
    return (cb_fcn_in_nleq2__user__routines_t *)F2PySwapThreadLocalCallbackPtr(key, ptr);
}

static cb_fcn_in_nleq2__user__routines_t *get_active_cb_fcn_in_nleq2__user__routines(void) {
    char *key = "__f2py_cb_cb_fcn_in_nleq2__user__routines";
    return (cb_fcn_in_nleq2__user__routines_t *)F2PyGetThreadLocalCallbackPtr(key);
}

#endif

/*typedef void(*cb_fcn_in_nleq2__user__routines_typedef)(int *,double *,double *,int *);*/
static int cb_fcn_in_nleq2__user__routines (int *n_cb_capi,double *x,double *f,int *ifail_cb_capi) {
    cb_fcn_in_nleq2__user__routines_t cb_local = { NULL, NULL, 0 };
    cb_fcn_in_nleq2__user__routines_t *cb = NULL;
    PyTupleObject *capi_arglist = NULL;
    PyObject *capi_return = NULL;
    PyObject *capi_tmp = NULL;
    PyObject *capi_arglist_list = NULL;
    int capi_j,capi_i = 0;
    int capi_longjmp_ok = 1;
/*decl*/
    int n=(*n_cb_capi);
    int ifail=(*ifail_cb_capi);
    npy_intp x_Dims[1] = {-1};
    npy_intp f_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
    cb = get_active_cb_fcn_in_nleq2__user__routines();
    if (cb == NULL) {
        capi_longjmp_ok = 0;
        cb = &cb_local;
    }
    capi_arglist = cb->args_capi;
    CFUNCSMESS("cb:Call-back function cb_fcn_in_nleq2__user__routines (maxnofargs=3(-1))\n");
    CFUNCSMESSPY("cb:cb_fcn_in_nleq2__user__routines_capi=",cb->capi);
    if (cb->capi==NULL) {
        capi_longjmp_ok = 0;
        cb->capi = PyObject_GetAttrString(nleq2_module,"fcn");
        CFUNCSMESSPY("cb:cb_fcn_in_nleq2__user__routines_capi=",cb->capi);
    }
    if (cb->capi==NULL) {
        PyErr_SetString(nleq2_error,"cb: Callback fcn not defined (as an argument or module nleq2 attribute).\n");
        goto capi_fail;
    }
    if (F2PyCapsule_Check(cb->capi)) {
    cb_fcn_in_nleq2__user__routines_typedef cb_fcn_in_nleq2__user__routines_cptr;
    cb_fcn_in_nleq2__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb->capi);
    (*cb_fcn_in_nleq2__user__routines_cptr)(n_cb_capi,x,f,ifail_cb_capi);
    return;
    }
    if (capi_arglist==NULL) {
        capi_longjmp_ok = 0;
        capi_tmp = PyObject_GetAttrString(nleq2_module,"fcn_extra_args");
        if (capi_tmp) {
            capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
            Py_DECREF(capi_tmp);
            if (capi_arglist==NULL) {
                PyErr_SetString(nleq2_error,"Failed to convert nleq2.fcn_extra_args to tuple.\n");
                goto capi_fail;
            }
        } else {
            PyErr_Clear();
            capi_arglist = (PyTupleObject *)Py_BuildValue("()");
        }
    }
    if (capi_arglist == NULL) {
        PyErr_SetString(nleq2_error,"Callback fcn argument list is not set.\n");
        goto capi_fail;
    }
/*setdims*/
    x_Dims[0]=n;
    f_Dims[0]=n;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
    capi_arglist_list = PySequence_List((PyObject *)capi_arglist);
    if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,x_Dims,NPY_DOUBLE,NULL,(char*)x,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
    if (cb->nofargs>capi_i)
        if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(ifail)))
            goto capi_fail;
    if (cb->nofargs>capi_i)
        if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
            goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
    CFUNCSMESS("cb:Call-back calling Python function fcn.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist_list);
    Py_DECREF(capi_arglist_list);
    capi_arglist_list = NULL;
#else
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
    CFUNCSMESSPY("cb:capi_return=",capi_return);
    if (capi_return == NULL) {
        fprintf(stderr,"capi_return is NULL\n");
        goto capi_fail;
    }
    if (capi_return == Py_None) {
        Py_DECREF(capi_return);
        capi_return = Py_BuildValue("()");
    }
    else if (!PyTuple_Check(capi_return)) {
        capi_return = Py_BuildValue("(N)",capi_return);
    }
    capi_j = PyTuple_Size(capi_return);
    capi_i = 0;
/*frompyobj*/
    if (capi_j>capi_i) {
        PyArrayObject *rv_cb_arr = NULL;
        if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
        rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,f_Dims,1,F2PY_INTENT_IN
,capi_tmp);
        if (rv_cb_arr == NULL) {
            fprintf(stderr,"rv_cb_arr is NULL\n");
            goto capi_fail;
        }
        MEMCOPY(f,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
        if (capi_tmp != (PyObject *)rv_cb_arr) {
            Py_DECREF(rv_cb_arr);
        }
    }
    if (capi_j>capi_i)
        GETSCALARFROMPYTUPLE(capi_return,capi_i++,ifail_cb_capi,int,"int_from_pyobj failed in converting argument ifail of call-back function cb_fcn_in_nleq2__user__routines to C int\n");
    CFUNCSMESS("cb:cb_fcn_in_nleq2__user__routines:successful\n");
    Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
    goto capi_return_pt;
capi_fail:
    fprintf(stderr,"Call-back cb_fcn_in_nleq2__user__routines failed.\n");
    Py_XDECREF(capi_return);
    Py_XDECREF(capi_arglist_list);
    if (capi_longjmp_ok) {
        longjmp(cb->jmpbuf,-1);
    }
capi_return_pt:
    ;
return 0;
}
/******************* end of cb_fcn_in_nleq2__user__routines *******************/


/********************** cb_jac_in_nleq2__user__routines **********************/
typedef struct {
    PyObject *capi;
    PyTupleObject *args_capi;
    int nofargs;
    jmp_buf jmpbuf;
} cb_jac_in_nleq2__user__routines_t;

#if defined(F2PY_THREAD_LOCAL_DECL) && !defined(F2PY_USE_PYTHON_TLS)

static F2PY_THREAD_LOCAL_DECL cb_jac_in_nleq2__user__routines_t *_active_cb_jac_in_nleq2__user__routines = NULL;

static cb_jac_in_nleq2__user__routines_t *swap_active_cb_jac_in_nleq2__user__routines(cb_jac_in_nleq2__user__routines_t *ptr) {
    cb_jac_in_nleq2__user__routines_t *prev = _active_cb_jac_in_nleq2__user__routines;
    _active_cb_jac_in_nleq2__user__routines = ptr;
    return prev;
}

static cb_jac_in_nleq2__user__routines_t *get_active_cb_jac_in_nleq2__user__routines(void) {
    return _active_cb_jac_in_nleq2__user__routines;
}

#else

static cb_jac_in_nleq2__user__routines_t *swap_active_cb_jac_in_nleq2__user__routines(cb_jac_in_nleq2__user__routines_t *ptr) {
    char *key = "__f2py_cb_cb_jac_in_nleq2__user__routines";
    return (cb_jac_in_nleq2__user__routines_t *)F2PySwapThreadLocalCallbackPtr(key, ptr);
}

static cb_jac_in_nleq2__user__routines_t *get_active_cb_jac_in_nleq2__user__routines(void) {
    char *key = "__f2py_cb_cb_jac_in_nleq2__user__routines";
    return (cb_jac_in_nleq2__user__routines_t *)F2PyGetThreadLocalCallbackPtr(key);
}

#endif

/*typedef void(*cb_jac_in_nleq2__user__routines_typedef)(int *,int *,double *,double *,int *);*/
static int cb_jac_in_nleq2__user__routines (int *n_cb_capi,int *m1_cb_capi,double *x,double *a,int *ifail_cb_capi) {
    cb_jac_in_nleq2__user__routines_t cb_local = { NULL, NULL, 0 };
    cb_jac_in_nleq2__user__routines_t *cb = NULL;
    PyTupleObject *capi_arglist = NULL;
    PyObject *capi_return = NULL;
    PyObject *capi_tmp = NULL;
    PyObject *capi_arglist_list = NULL;
    int capi_j,capi_i = 0;
    int capi_longjmp_ok = 1;
/*decl*/
    int n=(*n_cb_capi);
    int m1=(*m1_cb_capi);
    int ifail=(*ifail_cb_capi);
    npy_intp x_Dims[1] = {-1};
    npy_intp a_Dims[2] = {-1, -1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
    cb = get_active_cb_jac_in_nleq2__user__routines();
    if (cb == NULL) {
        capi_longjmp_ok = 0;
        cb = &cb_local;
    }
    capi_arglist = cb->args_capi;
    CFUNCSMESS("cb:Call-back function cb_jac_in_nleq2__user__routines (maxnofargs=3(-2))\n");
    CFUNCSMESSPY("cb:cb_jac_in_nleq2__user__routines_capi=",cb->capi);
    if (cb->capi==NULL) {
        capi_longjmp_ok = 0;
        cb->capi = PyObject_GetAttrString(nleq2_module,"jac");
        CFUNCSMESSPY("cb:cb_jac_in_nleq2__user__routines_capi=",cb->capi);
    }
    if (cb->capi==NULL) {
        PyErr_SetString(nleq2_error,"cb: Callback jac not defined (as an argument or module nleq2 attribute).\n");
        goto capi_fail;
    }
    if (F2PyCapsule_Check(cb->capi)) {
    cb_jac_in_nleq2__user__routines_typedef cb_jac_in_nleq2__user__routines_cptr;
    cb_jac_in_nleq2__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb->capi);
    (*cb_jac_in_nleq2__user__routines_cptr)(n_cb_capi,m1_cb_capi,x,a,ifail_cb_capi);
    return;
    }
    if (capi_arglist==NULL) {
        capi_longjmp_ok = 0;
        capi_tmp = PyObject_GetAttrString(nleq2_module,"jac_extra_args");
        if (capi_tmp) {
            capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
            Py_DECREF(capi_tmp);
            if (capi_arglist==NULL) {
                PyErr_SetString(nleq2_error,"Failed to convert nleq2.jac_extra_args to tuple.\n");
                goto capi_fail;
            }
        } else {
            PyErr_Clear();
            capi_arglist = (PyTupleObject *)Py_BuildValue("()");
        }
    }
    if (capi_arglist == NULL) {
        PyErr_SetString(nleq2_error,"Callback jac argument list is not set.\n");
        goto capi_fail;
    }
/*setdims*/
    x_Dims[0]=n;
    a_Dims[0]=m1,a_Dims[1]=n;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
    capi_arglist_list = PySequence_List((PyObject *)capi_arglist);
    if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,x_Dims,NPY_DOUBLE,NULL,(char*)x,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
    if (cb->nofargs>capi_i)
        if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
            goto capi_fail;
    if (cb->nofargs>capi_i)
        if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(m1)))
            goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
    CFUNCSMESS("cb:Call-back calling Python function jac.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist_list);
    Py_DECREF(capi_arglist_list);
    capi_arglist_list = NULL;
#else
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
    CFUNCSMESSPY("cb:capi_return=",capi_return);
    if (capi_return == NULL) {
        fprintf(stderr,"capi_return is NULL\n");
        goto capi_fail;
    }
    if (capi_return == Py_None) {
        Py_DECREF(capi_return);
        capi_return = Py_BuildValue("()");
    }
    else if (!PyTuple_Check(capi_return)) {
        capi_return = Py_BuildValue("(N)",capi_return);
    }
    capi_j = PyTuple_Size(capi_return);
    capi_i = 0;
/*frompyobj*/
    if (capi_j>capi_i) {
        PyArrayObject *rv_cb_arr = NULL;
        if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
        rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,a_Dims,2,F2PY_INTENT_IN
,capi_tmp);
        if (rv_cb_arr == NULL) {
            fprintf(stderr,"rv_cb_arr is NULL\n");
            goto capi_fail;
        }
        MEMCOPY(a,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
        if (capi_tmp != (PyObject *)rv_cb_arr) {
            Py_DECREF(rv_cb_arr);
        }
    }
    CFUNCSMESS("cb:cb_jac_in_nleq2__user__routines:successful\n");
    Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
    goto capi_return_pt;
capi_fail:
    fprintf(stderr,"Call-back cb_jac_in_nleq2__user__routines failed.\n");
    Py_XDECREF(capi_return);
    Py_XDECREF(capi_arglist_list);
    if (capi_longjmp_ok) {
        longjmp(cb->jmpbuf,-1);
    }
capi_return_pt:
    ;
return 0;
}
/******************* end of cb_jac_in_nleq2__user__routines *******************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** nleq2 ***********************************/
static char doc_f2py_rout_nleq2_nleq2[] = "\
x,xscal,rtol,iopt,ierr = nleq2(fcn,jac,x,xscal,rtol,iopt,iwk,rwk,[n,liwk,lrwk,fcn_extra_args,jac_extra_args])\n\nWrapper for ``nleq2``.\
\n\nParameters\n----------\n"
"fcn : call-back function\n"
"jac : call-back function\n"
"x : input rank-1 array('d') with bounds (n)\n"
"xscal : input rank-1 array('d') with bounds (n)\n"
"rtol : input float\n"
"iopt : input rank-1 array('i') with bounds (50)\n"
"iwk : input rank-1 array('i') with bounds (liwk)\n"
"rwk : input rank-1 array('d') with bounds (lrwk)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(x)\n"
"fcn_extra_args : input tuple, optional\n    Default: ()\n"
"jac_extra_args : input tuple, optional\n    Default: ()\n"
"liwk : input int, optional\n    Default: len(iwk)\n"
"lrwk : input int, optional\n    Default: len(rwk)\n"
"\nReturns\n-------\n"
"x : rank-1 array('d') with bounds (n)\n"
"xscal : rank-1 array('d') with bounds (n)\n"
"rtol : float\n"
"iopt : rank-1 array('i') with bounds (50)\n"
"ierr : int\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"    def fcn(x,ifail,[n]): return f,ifail\n\
    Required arguments:\n"
"        x : input rank-1 array('d') with bounds (n)\n"
"        ifail : input int\n"
"    Optional arguments:\n"
"        n : input int, optional\n    Default: len(x)\n"
"    Return objects:\n"
"        f : rank-1 array('d') with bounds (n)\n"
"        ifail : int\n"
"    def jac(x,[n,m1]): return a\n\
    Required arguments:\n"
"        x : input rank-1 array('d') with bounds (n)\n"
"    Optional arguments:\n"
"        n : input int, optional\n    Default: len(x)\n"
"        m1 : input int, optional\n    Default: shape(a,0)\n"
"    Return objects:\n"
"        a : rank-2 array('d') with bounds (m1,n)";
/* extern void F_FUNC(nleq2,NLEQ2)(int*,cb_fcn_in_nleq2__user__routines_typedef,cb_jac_in_nleq2__user__routines_typedef,double*,double*,double*,int*,int*,int*,int*,int*,double*); */
static PyObject *f2py_rout_nleq2_nleq2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(int*,cb_fcn_in_nleq2__user__routines_typedef,cb_jac_in_nleq2__user__routines_typedef,double*,double*,double*,int*,int*,int*,int*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n = 0;
    PyObject *n_capi = Py_None;
    cb_fcn_in_nleq2__user__routines_t fcn_cb = { Py_None, NULL, 0 };
    cb_fcn_in_nleq2__user__routines_t *fcn_cb_ptr = &fcn_cb;
    PyTupleObject *fcn_xa_capi = NULL;
    cb_fcn_in_nleq2__user__routines_typedef fcn_cptr;
    cb_jac_in_nleq2__user__routines_t jac_cb = { Py_None, NULL, 0 };
    cb_jac_in_nleq2__user__routines_t *jac_cb_ptr = &jac_cb;
    PyTupleObject *jac_xa_capi = NULL;
    cb_jac_in_nleq2__user__routines_typedef jac_cptr;
    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    double *xscal = NULL;
    npy_intp xscal_Dims[1] = {-1};
    const int xscal_Rank = 1;
    PyArrayObject *capi_xscal_as_array = NULL;
    int capi_xscal_intent = 0;
    PyObject *xscal_capi = Py_None;
    double rtol = 0;
    PyObject *rtol_capi = Py_None;
    int *iopt = NULL;
    npy_intp iopt_Dims[1] = {-1};
    const int iopt_Rank = 1;
    PyArrayObject *capi_iopt_as_array = NULL;
    int capi_iopt_intent = 0;
    PyObject *iopt_capi = Py_None;
    int ierr = 0;
    int liwk = 0;
    PyObject *liwk_capi = Py_None;
    int *iwk = NULL;
    npy_intp iwk_Dims[1] = {-1};
    const int iwk_Rank = 1;
    PyArrayObject *capi_iwk_as_array = NULL;
    int capi_iwk_intent = 0;
    PyObject *iwk_capi = Py_None;
    int lrwk = 0;
    PyObject *lrwk_capi = Py_None;
    double *rwk = NULL;
    npy_intp rwk_Dims[1] = {-1};
    const int rwk_Rank = 1;
    PyArrayObject *capi_rwk_as_array = NULL;
    int capi_rwk_intent = 0;
    PyObject *rwk_capi = Py_None;
    static char *capi_kwlist[] = {"fcn","jac","x","xscal","rtol","iopt","iwk","rwk","n","liwk","lrwk","fcn_extra_args","jac_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOO|OOOO!O!:nleq2.nleq2",\
        capi_kwlist,&fcn_cb.capi,&jac_cb.capi,&x_capi,&xscal_capi,&rtol_capi,&iopt_capi,&iwk_capi,&rwk_capi,&n_capi,&liwk_capi,&lrwk_capi,&PyTuple_Type,&fcn_xa_capi,&PyTuple_Type,&jac_xa_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable fcn */
if(F2PyCapsule_Check(fcn_cb.capi)) {
  fcn_cptr = F2PyCapsule_AsVoidPtr(fcn_cb.capi);
} else {
  fcn_cptr = cb_fcn_in_nleq2__user__routines;
}

    if (create_cb_arglist(fcn_cb.capi,fcn_xa_capi,3,1,&fcn_cb.nofargs,&fcn_cb.args_capi,"failed in processing argument list for call-back fcn.")) {

        CFUNCSMESS("Saving callback variables for `fcn`.\n");
        fcn_cb_ptr = swap_active_cb_fcn_in_nleq2__user__routines(fcn_cb_ptr);
    /* Processing variable jac */
if(F2PyCapsule_Check(jac_cb.capi)) {
  jac_cptr = F2PyCapsule_AsVoidPtr(jac_cb.capi);
} else {
  jac_cptr = cb_jac_in_nleq2__user__routines;
}

    if (create_cb_arglist(jac_cb.capi,jac_xa_capi,3,2,&jac_cb.nofargs,&jac_cb.args_capi,"failed in processing argument list for call-back jac.")) {

        CFUNCSMESS("Saving callback variables for `jac`.\n");
        jac_cb_ptr = swap_active_cb_jac_in_nleq2__user__routines(jac_cb_ptr);
    /* Processing variable x */
    ;
    capi_x_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char capi_errmess[] = "nleq2.nleq2.nleq2: failed to create array from the 3rd argument `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,x_Dims,x_Rank,  capi_x_intent,x_capi,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nleq2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (double *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable rtol */
        f2py_success = double_from_pyobj(&rtol,rtol_capi,"nleq2.nleq2() 5th argument (rtol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable iopt */
    iopt_Dims[0]=50;
    capi_iopt_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char capi_errmess[] = "nleq2.nleq2.nleq2: failed to create array from the 6th argument `iopt`";
    capi_iopt_as_array = ndarray_from_pyobj(  NPY_INT,1,iopt_Dims,iopt_Rank,  capi_iopt_intent,iopt_capi,capi_errmess);
    if (capi_iopt_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nleq2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iopt = (int *)(PyArray_DATA(capi_iopt_as_array));

    /* Processing variable ierr */
    /* Processing variable iwk */
    ;
    capi_iwk_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "nleq2.nleq2.nleq2: failed to create array from the 7th argument `iwk`";
    capi_iwk_as_array = ndarray_from_pyobj(  NPY_INT,1,iwk_Dims,iwk_Rank,  capi_iwk_intent,iwk_capi,capi_errmess);
    if (capi_iwk_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nleq2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iwk = (int *)(PyArray_DATA(capi_iwk_as_array));

    /* Processing variable rwk */
    ;
    capi_rwk_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "nleq2.nleq2.nleq2: failed to create array from the 8th argument `rwk`";
    capi_rwk_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rwk_Dims,rwk_Rank,  capi_rwk_intent,rwk_capi,capi_errmess);
    if (capi_rwk_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nleq2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rwk = (double *)(PyArray_DATA(capi_rwk_as_array));

    /* Processing variable n */
    if (n_capi == Py_None) n = len(x); else
        f2py_success = int_from_pyobj(&n,n_capi,"nleq2.nleq2() 1st keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(x)>=n,"len(x)>=n","1st keyword n","nleq2:n=%d",n) {
    /* Processing variable xscal */
    xscal_Dims[0]=n;
    capi_xscal_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char capi_errmess[] = "nleq2.nleq2.nleq2: failed to create array from the 4th argument `xscal`";
    capi_xscal_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,xscal_Dims,xscal_Rank,  capi_xscal_intent,xscal_capi,capi_errmess);
    if (capi_xscal_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nleq2_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xscal = (double *)(PyArray_DATA(capi_xscal_as_array));

    /* Processing variable liwk */
    if (liwk_capi == Py_None) liwk = len(iwk); else
        f2py_success = int_from_pyobj(&liwk,liwk_capi,"nleq2.nleq2() 2nd keyword (liwk) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(iwk)>=liwk,"len(iwk)>=liwk","2nd keyword liwk","nleq2:liwk=%d",liwk) {
    /* Processing variable lrwk */
    if (lrwk_capi == Py_None) lrwk = len(rwk); else
        f2py_success = int_from_pyobj(&lrwk,lrwk_capi,"nleq2.nleq2() 3rd keyword (lrwk) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(rwk)>=lrwk,"len(rwk)>=lrwk","3rd keyword lrwk","nleq2:lrwk=%d",lrwk) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        if ((setjmp(fcn_cb.jmpbuf)) || (setjmp(jac_cb.jmpbuf))) {
            f2py_success = 0;
        } else {
                (*f2py_func)(&n,fcn_cptr,jac_cptr,x,xscal,&rtol,iopt,&ierr,&liwk,iwk,&lrwk,rwk);
        }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNdNi",capi_x_as_array,capi_xscal_as_array,rtol,capi_iopt_as_array,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(len(rwk)>=lrwk)*/
    } /*if (f2py_success) of lrwk*/
    /* End of cleaning variable lrwk */
    } /*CHECKSCALAR(len(iwk)>=liwk)*/
    } /*if (f2py_success) of liwk*/
    /* End of cleaning variable liwk */
    }  /* if (capi_xscal_as_array == NULL) ... else of xscal */
    /* End of cleaning variable xscal */
    } /*CHECKSCALAR(len(x)>=n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    if((PyObject *)capi_rwk_as_array!=rwk_capi) {
        Py_XDECREF(capi_rwk_as_array); }
    }  /* if (capi_rwk_as_array == NULL) ... else of rwk */
    /* End of cleaning variable rwk */
    if((PyObject *)capi_iwk_as_array!=iwk_capi) {
        Py_XDECREF(capi_iwk_as_array); }
    }  /* if (capi_iwk_as_array == NULL) ... else of iwk */
    /* End of cleaning variable iwk */
    /* End of cleaning variable ierr */
    }  /* if (capi_iopt_as_array == NULL) ... else of iopt */
    /* End of cleaning variable iopt */
    } /*if (f2py_success) of rtol*/
    /* End of cleaning variable rtol */
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
        CFUNCSMESS("Restoring callback variables for `jac`.\n");
        jac_cb_ptr = swap_active_cb_jac_in_nleq2__user__routines(jac_cb_ptr);
        Py_DECREF(jac_cb.args_capi);
    }
    /* End of cleaning variable jac */
        CFUNCSMESS("Restoring callback variables for `fcn`.\n");
        fcn_cb_ptr = swap_active_cb_fcn_in_nleq2__user__routines(fcn_cb_ptr);
        Py_DECREF(fcn_cb.args_capi);
    }
    /* End of cleaning variable fcn */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of nleq2 ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"nleq2",-1,{{-1}},0,0,(char *)  F_FUNC(nleq2,NLEQ2),  (f2py_init_func)f2py_rout_nleq2_nleq2,doc_f2py_rout_nleq2_nleq2},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "nleq2",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_nleq2(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = nleq2_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module nleq2 (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'nleq2' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    x,xscal,rtol,iopt,ierr = nleq2(fcn,jac,x,xscal,rtol,iopt,iwk,rwk,n=len(x),liwk=len(iwk),lrwk=len(rwk),fcn_extra_args=(),jac_extra_args=())\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    nleq2_error = PyErr_NewException ("nleq2.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_nleq2_error", nleq2_error);
    Py_DECREF(nleq2_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"nleq2");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
