/* File: pitconmodule.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Oct 16 14:17:22 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *pitcon_error;
static PyObject *pitcon_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef int(*cb_fx_in_pitcon1__user__routines_typedef)(int *,double *,int *,double *,double *,int *);
typedef int(*cb_df_in_pitcon1__user__routines_typedef)(int *,double *,int *,double *,double *,int *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

/* The following subroutine was added after the f2c translation */
double d_sign(double *a, double *b)
{
  double x;
  x = (*a >= 0 ? *a : - *a);
  return( *b >= 0 ? x : -x);
}

double pow_dd(double *ap, double *bp)
{
return(pow(*ap, *bp) );
}

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"pitcon.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)


#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)


#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
        if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
        if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
            goto capi_fail;\
    }


#define pyobj_from_int1(v) (PyLong_FromLong(v))


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef F2PY_THREAD_LOCAL_DECL
#if defined(_MSC_VER)
#define F2PY_THREAD_LOCAL_DECL __declspec(thread)
#elif defined(NPY_OS_MINGW)
#define F2PY_THREAD_LOCAL_DECL __thread
#elif defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
#define F2PY_THREAD_LOCAL_DECL _Thread_local
#elif defined(__GNUC__) \
      && (__GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ >= 4)))
#define F2PY_THREAD_LOCAL_DECL __thread
#endif
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(pitcon_error,errstring);\
        /*goto capi_fail;*/\
    } else

/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = pitcon_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
create_cb_arglist(PyObject* fun, PyTupleObject* xa , const int maxnofargs,
                  const int nofoptargs, int *nofargs, PyTupleObject **args,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    Py_ssize_t tot, opt, ext, siz, i, di = 0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun)) {
        tmp_fun = fun;
        Py_INCREF(tmp_fun);
    }
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                Py_INCREF(tmp_fun);
                tot = maxnofargs;
                if (PyCFunction_Check(fun)) {
                    /* In case the function has a co_argcount (like on PyPy) */
                    di = 0;
                }
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
            Py_INCREF(tmp_fun);
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with PyCapsule call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
            Py_INCREF(tmp_fun);
        }
    }

    if (tmp_fun == NULL) {
        fprintf(stderr,
                "Call-back argument must be function|instance|instance.__call__|f2py-function "
                "but got %s.\n",
                ((fun == NULL) ? "NULL" : Py_TYPE(fun)->tp_name));
        goto capi_fail;
    }

    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount")) {
            PyObject *tmp_argcount = PyObject_GetAttrString(tmp,"co_argcount");
            Py_DECREF(tmp);
            if (tmp_argcount == NULL) {
                goto capi_fail;
            }
            tot = PyLong_AsSsize_t(tmp_argcount) - di;
            Py_DECREF(tmp_argcount);
        }
    }
    /* Get the number of optional arguments */
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);

#ifdef DEBUGCFUNCS
    fprintf(stderr,
            "debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),"
            "tot,opt,ext,siz,nofargs = %d(-%d), %zd, %zd, %zd, %zd, %d\n",
            maxnofargs, nofoptargs, tot, opt, ext, siz, *nofargs);
#endif

    if (siz < tot-opt) {
        fprintf(stderr,
                "create_cb_arglist: Failed to build argument list "
                "(siz) with enough arguments (tot-opt) required by "
                "user-supplied function (siz,tot,opt=%zd, %zd, %zd).\n",
                siz, tot, opt);
        goto capi_fail;
    }

    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    Py_DECREF(tmp_fun);
    return 1;

capi_fail:
    if (PyErr_Occurred() == NULL)
        PyErr_SetString(pitcon_error, errmess);
    Py_XDECREF(tmp_fun);
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern int F_FUNC(pitcon1,PITCON1)(cb_df_in_pitcon1__user__routines_typedef,double*,cb_fx_in_pitcon1__user__routines_typedef,int*,int*,int*,int*,int*,double*,int*,double*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/********************** cb_df_in_pitcon1__user__routines **********************/
typedef struct {
    PyObject *capi;
    PyTupleObject *args_capi;
    int nofargs;
    jmp_buf jmpbuf;
} cb_df_in_pitcon1__user__routines_t;

#if defined(F2PY_THREAD_LOCAL_DECL) && !defined(F2PY_USE_PYTHON_TLS)

static F2PY_THREAD_LOCAL_DECL cb_df_in_pitcon1__user__routines_t *_active_cb_df_in_pitcon1__user__routines = NULL;

static cb_df_in_pitcon1__user__routines_t *swap_active_cb_df_in_pitcon1__user__routines(cb_df_in_pitcon1__user__routines_t *ptr) {
    cb_df_in_pitcon1__user__routines_t *prev = _active_cb_df_in_pitcon1__user__routines;
    _active_cb_df_in_pitcon1__user__routines = ptr;
    return prev;
}

static cb_df_in_pitcon1__user__routines_t *get_active_cb_df_in_pitcon1__user__routines(void) {
    return _active_cb_df_in_pitcon1__user__routines;
}

#else

static cb_df_in_pitcon1__user__routines_t *swap_active_cb_df_in_pitcon1__user__routines(cb_df_in_pitcon1__user__routines_t *ptr) {
    char *key = "__f2py_cb_cb_df_in_pitcon1__user__routines";
    return (cb_df_in_pitcon1__user__routines_t *)F2PySwapThreadLocalCallbackPtr(key, ptr);
}

static cb_df_in_pitcon1__user__routines_t *get_active_cb_df_in_pitcon1__user__routines(void) {
    char *key = "__f2py_cb_cb_df_in_pitcon1__user__routines";
    return (cb_df_in_pitcon1__user__routines_t *)F2PyGetThreadLocalCallbackPtr(key);
}

#endif

/*typedef void(*cb_df_in_pitcon1__user__routines_typedef)(int *,double *,int *,double *,double *,int *);*/
static int cb_df_in_pitcon1__user__routines (int *nvar_cb_capi,double *fpar,int *ipar,double *x,double *fjac,int *ierror_cb_capi) {
    cb_df_in_pitcon1__user__routines_t cb_local = { NULL, NULL, 0 };
    cb_df_in_pitcon1__user__routines_t *cb = NULL;
    PyTupleObject *capi_arglist = NULL;
    PyObject *capi_return = NULL;
    PyObject *capi_tmp = NULL;
    PyObject *capi_arglist_list = NULL;
    int capi_j,capi_i = 0;
    int capi_longjmp_ok = 1;
/*decl*/
    int nvar=(*nvar_cb_capi);
    int ierror=(*ierror_cb_capi);
    npy_intp fpar_Dims[1] = {-1};
    npy_intp ipar_Dims[1] = {-1};
    npy_intp x_Dims[1] = {-1};
    npy_intp fjac_Dims[2] = {-1, -1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
    cb = get_active_cb_df_in_pitcon1__user__routines();
    if (cb == NULL) {
        capi_longjmp_ok = 0;
        cb = &cb_local;
    }
    capi_arglist = cb->args_capi;
    CFUNCSMESS("cb:Call-back function cb_df_in_pitcon1__user__routines (maxnofargs=2(-1))\n");
    CFUNCSMESSPY("cb:cb_df_in_pitcon1__user__routines_capi=",cb->capi);
    if (cb->capi==NULL) {
        capi_longjmp_ok = 0;
        cb->capi = PyObject_GetAttrString(pitcon_module,"df");
        CFUNCSMESSPY("cb:cb_df_in_pitcon1__user__routines_capi=",cb->capi);
    }
    if (cb->capi==NULL) {
        PyErr_SetString(pitcon_error,"cb: Callback df not defined (as an argument or module pitcon attribute).\n");
        goto capi_fail;
    }
    if (F2PyCapsule_Check(cb->capi)) {
    cb_df_in_pitcon1__user__routines_typedef cb_df_in_pitcon1__user__routines_cptr;
    cb_df_in_pitcon1__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb->capi);
    (*cb_df_in_pitcon1__user__routines_cptr)(nvar_cb_capi,fpar,ipar,x,fjac,ierror_cb_capi);
    return;
    }
    if (capi_arglist==NULL) {
        capi_longjmp_ok = 0;
        capi_tmp = PyObject_GetAttrString(pitcon_module,"df_extra_args");
        if (capi_tmp) {
            capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
            Py_DECREF(capi_tmp);
            if (capi_arglist==NULL) {
                PyErr_SetString(pitcon_error,"Failed to convert pitcon.df_extra_args to tuple.\n");
                goto capi_fail;
            }
        } else {
            PyErr_Clear();
            capi_arglist = (PyTupleObject *)Py_BuildValue("()");
        }
    }
    if (capi_arglist == NULL) {
        PyErr_SetString(pitcon_error,"Callback df argument list is not set.\n");
        goto capi_fail;
    }
/*setdims*/
    fpar_Dims[0]=nvar;
    ipar_Dims[0]=nvar;
    x_Dims[0]=nvar;
    fjac_Dims[0]=nvar,fjac_Dims[1]=nvar;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
    capi_arglist_list = PySequence_List((PyObject *)capi_arglist);
    if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,x_Dims,NPY_DOUBLE,NULL,(char*)x,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
    if (cb->nofargs>capi_i)
        if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(nvar)))
            goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
    CFUNCSMESS("cb:Call-back calling Python function df.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist_list);
    Py_DECREF(capi_arglist_list);
    capi_arglist_list = NULL;
#else
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
    CFUNCSMESSPY("cb:capi_return=",capi_return);
    if (capi_return == NULL) {
        fprintf(stderr,"capi_return is NULL\n");
        goto capi_fail;
    }
    if (capi_return == Py_None) {
        Py_DECREF(capi_return);
        capi_return = Py_BuildValue("()");
    }
    else if (!PyTuple_Check(capi_return)) {
        capi_return = Py_BuildValue("(N)",capi_return);
    }
    capi_j = PyTuple_Size(capi_return);
    capi_i = 0;
/*frompyobj*/
    if (capi_j>capi_i) {
        PyArrayObject *rv_cb_arr = NULL;
        if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
        rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,fjac_Dims,2,F2PY_INTENT_IN
,capi_tmp);
        if (rv_cb_arr == NULL) {
            fprintf(stderr,"rv_cb_arr is NULL\n");
            goto capi_fail;
        }
        MEMCOPY(fjac,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
        if (capi_tmp != (PyObject *)rv_cb_arr) {
            Py_DECREF(rv_cb_arr);
        }
    }
    if (capi_j>capi_i)
        GETSCALARFROMPYTUPLE(capi_return,capi_i++,ierror_cb_capi,int,"int_from_pyobj failed in converting argument ierror of call-back function cb_df_in_pitcon1__user__routines to C int\n");
    CFUNCSMESS("cb:cb_df_in_pitcon1__user__routines:successful\n");
    Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
    goto capi_return_pt;
capi_fail:
    fprintf(stderr,"Call-back cb_df_in_pitcon1__user__routines failed.\n");
    Py_XDECREF(capi_return);
    Py_XDECREF(capi_arglist_list);
    if (capi_longjmp_ok) {
        longjmp(cb->jmpbuf,-1);
    }
capi_return_pt:
    ;
return 0;
}
/****************** end of cb_df_in_pitcon1__user__routines ******************/


/********************** cb_fx_in_pitcon1__user__routines **********************/
typedef struct {
    PyObject *capi;
    PyTupleObject *args_capi;
    int nofargs;
    jmp_buf jmpbuf;
} cb_fx_in_pitcon1__user__routines_t;

#if defined(F2PY_THREAD_LOCAL_DECL) && !defined(F2PY_USE_PYTHON_TLS)

static F2PY_THREAD_LOCAL_DECL cb_fx_in_pitcon1__user__routines_t *_active_cb_fx_in_pitcon1__user__routines = NULL;

static cb_fx_in_pitcon1__user__routines_t *swap_active_cb_fx_in_pitcon1__user__routines(cb_fx_in_pitcon1__user__routines_t *ptr) {
    cb_fx_in_pitcon1__user__routines_t *prev = _active_cb_fx_in_pitcon1__user__routines;
    _active_cb_fx_in_pitcon1__user__routines = ptr;
    return prev;
}

static cb_fx_in_pitcon1__user__routines_t *get_active_cb_fx_in_pitcon1__user__routines(void) {
    return _active_cb_fx_in_pitcon1__user__routines;
}

#else

static cb_fx_in_pitcon1__user__routines_t *swap_active_cb_fx_in_pitcon1__user__routines(cb_fx_in_pitcon1__user__routines_t *ptr) {
    char *key = "__f2py_cb_cb_fx_in_pitcon1__user__routines";
    return (cb_fx_in_pitcon1__user__routines_t *)F2PySwapThreadLocalCallbackPtr(key, ptr);
}

static cb_fx_in_pitcon1__user__routines_t *get_active_cb_fx_in_pitcon1__user__routines(void) {
    char *key = "__f2py_cb_cb_fx_in_pitcon1__user__routines";
    return (cb_fx_in_pitcon1__user__routines_t *)F2PyGetThreadLocalCallbackPtr(key);
}

#endif

/*typedef void(*cb_fx_in_pitcon1__user__routines_typedef)(int *,double *,int *,double *,double *,int *);*/
static int cb_fx_in_pitcon1__user__routines (int *nvar_cb_capi,double *fpar,int *ipar,double *x,double *fvec,int *ierror_cb_capi) {
    cb_fx_in_pitcon1__user__routines_t cb_local = { NULL, NULL, 0 };
    cb_fx_in_pitcon1__user__routines_t *cb = NULL;
    PyTupleObject *capi_arglist = NULL;
    PyObject *capi_return = NULL;
    PyObject *capi_tmp = NULL;
    PyObject *capi_arglist_list = NULL;
    int capi_j,capi_i = 0;
    int capi_longjmp_ok = 1;
/*decl*/
    int nvar=(*nvar_cb_capi);
    int ierror=(*ierror_cb_capi);
    npy_intp fpar_Dims[1] = {-1};
    npy_intp ipar_Dims[1] = {-1};
    npy_intp x_Dims[1] = {-1};
    npy_intp fvec_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
    cb = get_active_cb_fx_in_pitcon1__user__routines();
    if (cb == NULL) {
        capi_longjmp_ok = 0;
        cb = &cb_local;
    }
    capi_arglist = cb->args_capi;
    CFUNCSMESS("cb:Call-back function cb_fx_in_pitcon1__user__routines (maxnofargs=2(-1))\n");
    CFUNCSMESSPY("cb:cb_fx_in_pitcon1__user__routines_capi=",cb->capi);
    if (cb->capi==NULL) {
        capi_longjmp_ok = 0;
        cb->capi = PyObject_GetAttrString(pitcon_module,"fx");
        CFUNCSMESSPY("cb:cb_fx_in_pitcon1__user__routines_capi=",cb->capi);
    }
    if (cb->capi==NULL) {
        PyErr_SetString(pitcon_error,"cb: Callback fx not defined (as an argument or module pitcon attribute).\n");
        goto capi_fail;
    }
    if (F2PyCapsule_Check(cb->capi)) {
    cb_fx_in_pitcon1__user__routines_typedef cb_fx_in_pitcon1__user__routines_cptr;
    cb_fx_in_pitcon1__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb->capi);
    (*cb_fx_in_pitcon1__user__routines_cptr)(nvar_cb_capi,fpar,ipar,x,fvec,ierror_cb_capi);
    return;
    }
    if (capi_arglist==NULL) {
        capi_longjmp_ok = 0;
        capi_tmp = PyObject_GetAttrString(pitcon_module,"fx_extra_args");
        if (capi_tmp) {
            capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
            Py_DECREF(capi_tmp);
            if (capi_arglist==NULL) {
                PyErr_SetString(pitcon_error,"Failed to convert pitcon.fx_extra_args to tuple.\n");
                goto capi_fail;
            }
        } else {
            PyErr_Clear();
            capi_arglist = (PyTupleObject *)Py_BuildValue("()");
        }
    }
    if (capi_arglist == NULL) {
        PyErr_SetString(pitcon_error,"Callback fx argument list is not set.\n");
        goto capi_fail;
    }
/*setdims*/
    fpar_Dims[0]=nvar;
    ipar_Dims[0]=nvar;
    x_Dims[0]=nvar;
    fvec_Dims[0]=nvar;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
    capi_arglist_list = PySequence_List((PyObject *)capi_arglist);
    if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
    if (cb->nofargs>capi_i) {
        /* tmp_arr will be inserted to capi_arglist_list that will be
           destroyed when leaving callback function wrapper together
           with tmp_arr. */
        PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,
          1,x_Dims,NPY_DOUBLE,NULL,(char*)x,1,
          NPY_ARRAY_FARRAY,NULL);


        if (tmp_arr==NULL)
            goto capi_fail;
        if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
            goto capi_fail;
}
    if (cb->nofargs>capi_i)
        if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(nvar)))
            goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
    CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
    CFUNCSMESS("cb:Call-back calling Python function fx.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist_list);
    Py_DECREF(capi_arglist_list);
    capi_arglist_list = NULL;
#else
    capi_return = PyObject_CallObject(cb->capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
    CFUNCSMESSPY("cb:capi_return=",capi_return);
    if (capi_return == NULL) {
        fprintf(stderr,"capi_return is NULL\n");
        goto capi_fail;
    }
    if (capi_return == Py_None) {
        Py_DECREF(capi_return);
        capi_return = Py_BuildValue("()");
    }
    else if (!PyTuple_Check(capi_return)) {
        capi_return = Py_BuildValue("(N)",capi_return);
    }
    capi_j = PyTuple_Size(capi_return);
    capi_i = 0;
/*frompyobj*/
    if (capi_j>capi_i) {
        PyArrayObject *rv_cb_arr = NULL;
        if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
        rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,fvec_Dims,1,F2PY_INTENT_IN
,capi_tmp);
        if (rv_cb_arr == NULL) {
            fprintf(stderr,"rv_cb_arr is NULL\n");
            goto capi_fail;
        }
        MEMCOPY(fvec,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
        if (capi_tmp != (PyObject *)rv_cb_arr) {
            Py_DECREF(rv_cb_arr);
        }
    }
    if (capi_j>capi_i)
        GETSCALARFROMPYTUPLE(capi_return,capi_i++,ierror_cb_capi,int,"int_from_pyobj failed in converting argument ierror of call-back function cb_fx_in_pitcon1__user__routines to C int\n");
    CFUNCSMESS("cb:cb_fx_in_pitcon1__user__routines:successful\n");
    Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
    goto capi_return_pt;
capi_fail:
    fprintf(stderr,"Call-back cb_fx_in_pitcon1__user__routines failed.\n");
    Py_XDECREF(capi_return);
    Py_XDECREF(capi_arglist_list);
    if (capi_longjmp_ok) {
        longjmp(cb->jmpbuf,-1);
    }
capi_return_pt:
    ;
return 0;
}
/****************** end of cb_fx_in_pitcon1__user__routines ******************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** pitcon1 **********************************/
static char doc_f2py_rout_pitcon_pitcon1[] = "\
ierror,iwork,rwork,xr = pitcon1(df,fpar,fx,ipar,iwork,rwork,xr,[liw,nvar,lrw,imth,df_extra_args,fx_extra_args,overwrite_iwork,overwrite_rwork,overwrite_xr])\n\nWrapper for ``pitcon1``.\
\n\nParameters\n----------\n"
"df : call-back function\n"
"fpar : input rank-1 array('d') with bounds (*)\n"
"fx : call-back function\n"
"ipar : input rank-1 array('i') with bounds (*)\n"
"iwork : input rank-1 array('i') with bounds (liw)\n"
"rwork : input rank-1 array('d') with bounds (lrw)\n"
"xr : input rank-1 array('d') with bounds (nvar)\n"
"\nOther Parameters\n----------------\n"
"df_extra_args : input tuple, optional\n    Default: ()\n"
"fx_extra_args : input tuple, optional\n    Default: ()\n"
"overwrite_iwork : input int, optional\n    Default: 0\n"
"liw : input int, optional\n    Default: len(iwork)\n"
"nvar : input int, optional\n    Default: len(xr)\n"
"overwrite_rwork : input int, optional\n    Default: 0\n"
"lrw : input int, optional\n    Default: len(rwork)\n"
"overwrite_xr : input int, optional\n    Default: 0\n"
"imth : input int, optional\n    Default: 1\n"
"\nReturns\n-------\n"
"ierror : int\n"
"iwork : rank-1 array('i') with bounds (liw)\n"
"rwork : rank-1 array('d') with bounds (lrw)\n"
"xr : rank-1 array('d') with bounds (nvar)\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"    def df(x,[nvar]): return fjac,ierror\n\
    Required arguments:\n"
"        x : input rank-1 array('d') with bounds (nvar)\n"
"    Optional arguments:\n"
"        nvar : input int, optional\n    Default: len(xr)\n"
"    Return objects:\n"
"        fjac : rank-2 array('d') with bounds (nvar,nvar)\n"
"        ierror : int\n"
"    def fx(x,[nvar]): return fvec,ierror\n\
    Required arguments:\n"
"        x : input rank-1 array('d') with bounds (nvar)\n"
"    Optional arguments:\n"
"        nvar : input int, optional\n    Default: len(xr)\n"
"    Return objects:\n"
"        fvec : rank-1 array('d') with bounds (nvar)\n"
"        ierror : int";
/* extern void F_FUNC(pitcon1,PITCON1)(cb_df_in_pitcon1__user__routines_typedef,double*,cb_fx_in_pitcon1__user__routines_typedef,int*,int*,int*,int*,int*,double*,int*,double*,int*); */
static PyObject *f2py_rout_pitcon_pitcon1(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(cb_df_in_pitcon1__user__routines_typedef,double*,cb_fx_in_pitcon1__user__routines_typedef,int*,int*,int*,int*,int*,double*,int*,double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    cb_df_in_pitcon1__user__routines_t df_cb = { Py_None, NULL, 0 };
    cb_df_in_pitcon1__user__routines_t *df_cb_ptr = &df_cb;
    PyTupleObject *df_xa_capi = NULL;
    cb_df_in_pitcon1__user__routines_typedef df_cptr;
    double *fpar = NULL;
    npy_intp fpar_Dims[1] = {-1};
    const int fpar_Rank = 1;
    PyArrayObject *capi_fpar_as_array = NULL;
    int capi_fpar_intent = 0;
    PyObject *fpar_capi = Py_None;
    cb_fx_in_pitcon1__user__routines_t fx_cb = { Py_None, NULL, 0 };
    cb_fx_in_pitcon1__user__routines_t *fx_cb_ptr = &fx_cb;
    PyTupleObject *fx_xa_capi = NULL;
    cb_fx_in_pitcon1__user__routines_typedef fx_cptr;
    int ierror = 0;
    int *ipar = NULL;
    npy_intp ipar_Dims[1] = {-1};
    const int ipar_Rank = 1;
    PyArrayObject *capi_ipar_as_array = NULL;
    int capi_ipar_intent = 0;
    PyObject *ipar_capi = Py_None;
    int *iwork = NULL;
    npy_intp iwork_Dims[1] = {-1};
    const int iwork_Rank = 1;
    PyArrayObject *capi_iwork_as_array = NULL;
    int capi_iwork_intent = 0;
    int capi_overwrite_iwork = 0;
    PyObject *iwork_capi = Py_None;
    int liw = 0;
    PyObject *liw_capi = Py_None;
    int nvar = 0;
    PyObject *nvar_capi = Py_None;
    double *rwork = NULL;
    npy_intp rwork_Dims[1] = {-1};
    const int rwork_Rank = 1;
    PyArrayObject *capi_rwork_as_array = NULL;
    int capi_rwork_intent = 0;
    int capi_overwrite_rwork = 0;
    PyObject *rwork_capi = Py_None;
    int lrw = 0;
    PyObject *lrw_capi = Py_None;
    double *xr = NULL;
    npy_intp xr_Dims[1] = {-1};
    const int xr_Rank = 1;
    PyArrayObject *capi_xr_as_array = NULL;
    int capi_xr_intent = 0;
    int capi_overwrite_xr = 0;
    PyObject *xr_capi = Py_None;
    int imth = 0;
    PyObject *imth_capi = Py_None;
    static char *capi_kwlist[] = {"df","fpar","fx","ipar","iwork","rwork","xr","liw","nvar","lrw","imth","df_extra_args","fx_extra_args","overwrite_iwork","overwrite_rwork","overwrite_xr",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOO|OOOOO!O!iii:pitcon.pitcon1",\
        capi_kwlist,&df_cb.capi,&fpar_capi,&fx_cb.capi,&ipar_capi,&iwork_capi,&rwork_capi,&xr_capi,&liw_capi,&nvar_capi,&lrw_capi,&imth_capi,&PyTuple_Type,&df_xa_capi,&PyTuple_Type,&fx_xa_capi,&capi_overwrite_iwork,&capi_overwrite_rwork,&capi_overwrite_xr))
        return NULL;
/*frompyobj*/
    /* Processing variable df */
if(F2PyCapsule_Check(df_cb.capi)) {
  df_cptr = F2PyCapsule_AsVoidPtr(df_cb.capi);
} else {
  df_cptr = cb_df_in_pitcon1__user__routines;
}

    if (create_cb_arglist(df_cb.capi,df_xa_capi,2,1,&df_cb.nofargs,&df_cb.args_capi,"failed in processing argument list for call-back df.")) {

        CFUNCSMESS("Saving callback variables for `df`.\n");
        df_cb_ptr = swap_active_cb_df_in_pitcon1__user__routines(df_cb_ptr);
    /* Processing variable fpar */
    ;
    capi_fpar_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "pitcon.pitcon.pitcon1: failed to create array from the 2nd argument `fpar`";
    capi_fpar_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,fpar_Dims,fpar_Rank,  capi_fpar_intent,fpar_capi,capi_errmess);
    if (capi_fpar_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = pitcon_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        fpar = (double *)(PyArray_DATA(capi_fpar_as_array));

    /* Processing variable fx */
if(F2PyCapsule_Check(fx_cb.capi)) {
  fx_cptr = F2PyCapsule_AsVoidPtr(fx_cb.capi);
} else {
  fx_cptr = cb_fx_in_pitcon1__user__routines;
}

    if (create_cb_arglist(fx_cb.capi,fx_xa_capi,2,1,&fx_cb.nofargs,&fx_cb.args_capi,"failed in processing argument list for call-back fx.")) {

        CFUNCSMESS("Saving callback variables for `fx`.\n");
        fx_cb_ptr = swap_active_cb_fx_in_pitcon1__user__routines(fx_cb_ptr);
    /* Processing variable ierror */
    /* Processing variable ipar */
    ;
    capi_ipar_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "pitcon.pitcon.pitcon1: failed to create array from the 4th argument `ipar`";
    capi_ipar_as_array = ndarray_from_pyobj(  NPY_INT,1,ipar_Dims,ipar_Rank,  capi_ipar_intent,ipar_capi,capi_errmess);
    if (capi_ipar_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = pitcon_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ipar = (int *)(PyArray_DATA(capi_ipar_as_array));

    /* Processing variable iwork */
    capi_iwork_intent |= (capi_overwrite_iwork?0:F2PY_INTENT_COPY);
    ;
    capi_iwork_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char capi_errmess[] = "pitcon.pitcon.pitcon1: failed to create array from the 5th argument `iwork`";
    capi_iwork_as_array = ndarray_from_pyobj(  NPY_INT,1,iwork_Dims,iwork_Rank,  capi_iwork_intent,iwork_capi,capi_errmess);
    if (capi_iwork_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = pitcon_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        iwork = (int *)(PyArray_DATA(capi_iwork_as_array));

    /* Processing variable rwork */
    capi_rwork_intent |= (capi_overwrite_rwork?0:F2PY_INTENT_COPY);
    ;
    capi_rwork_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char capi_errmess[] = "pitcon.pitcon.pitcon1: failed to create array from the 6th argument `rwork`";
    capi_rwork_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rwork_Dims,rwork_Rank,  capi_rwork_intent,rwork_capi,capi_errmess);
    if (capi_rwork_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = pitcon_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rwork = (double *)(PyArray_DATA(capi_rwork_as_array));

    /* Processing variable xr */
    capi_xr_intent |= (capi_overwrite_xr?0:F2PY_INTENT_COPY);
    ;
    capi_xr_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char capi_errmess[] = "pitcon.pitcon.pitcon1: failed to create array from the 7th argument `xr`";
    capi_xr_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,xr_Dims,xr_Rank,  capi_xr_intent,xr_capi,capi_errmess);
    if (capi_xr_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = pitcon_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xr = (double *)(PyArray_DATA(capi_xr_as_array));

    /* Processing variable imth */
    if (imth_capi == Py_None) imth = 1; else
        f2py_success = int_from_pyobj(&imth,imth_capi,"pitcon.pitcon1() 4th keyword (imth) can't be converted to int");
    if (f2py_success) {
    /* Processing variable liw */
    if (liw_capi == Py_None) liw = len(iwork); else
        f2py_success = int_from_pyobj(&liw,liw_capi,"pitcon.pitcon1() 1st keyword (liw) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(iwork)>=liw,"len(iwork)>=liw","1st keyword liw","pitcon1:liw=%d",liw) {
    /* Processing variable nvar */
    if (nvar_capi == Py_None) nvar = len(xr); else
        f2py_success = int_from_pyobj(&nvar,nvar_capi,"pitcon.pitcon1() 2nd keyword (nvar) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(xr)>=nvar,"len(xr)>=nvar","2nd keyword nvar","pitcon1:nvar=%d",nvar) {
    /* Processing variable lrw */
    if (lrw_capi == Py_None) lrw = len(rwork); else
        f2py_success = int_from_pyobj(&lrw,lrw_capi,"pitcon.pitcon1() 3rd keyword (lrw) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(rwork)>=lrw,"len(rwork)>=lrw","3rd keyword lrw","pitcon1:lrw=%d",lrw) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        if ((setjmp(df_cb.jmpbuf)) || (setjmp(fx_cb.jmpbuf))) {
            f2py_success = 0;
        } else {
                (*f2py_func)(df_cptr,fpar,fx_cptr,&ierror,ipar,iwork,&liw,&nvar,rwork,&lrw,xr,&imth);
        }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("iNNN",ierror,capi_iwork_as_array,capi_rwork_as_array,capi_xr_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(len(rwork)>=lrw)*/
    } /*if (f2py_success) of lrw*/
    /* End of cleaning variable lrw */
    } /*CHECKSCALAR(len(xr)>=nvar)*/
    } /*if (f2py_success) of nvar*/
    /* End of cleaning variable nvar */
    } /*CHECKSCALAR(len(iwork)>=liw)*/
    } /*if (f2py_success) of liw*/
    /* End of cleaning variable liw */
    } /*if (f2py_success) of imth*/
    /* End of cleaning variable imth */
    }  /* if (capi_xr_as_array == NULL) ... else of xr */
    /* End of cleaning variable xr */
    }  /* if (capi_rwork_as_array == NULL) ... else of rwork */
    /* End of cleaning variable rwork */
    }  /* if (capi_iwork_as_array == NULL) ... else of iwork */
    /* End of cleaning variable iwork */
    if((PyObject *)capi_ipar_as_array!=ipar_capi) {
        Py_XDECREF(capi_ipar_as_array); }
    }  /* if (capi_ipar_as_array == NULL) ... else of ipar */
    /* End of cleaning variable ipar */
    /* End of cleaning variable ierror */
        CFUNCSMESS("Restoring callback variables for `fx`.\n");
        fx_cb_ptr = swap_active_cb_fx_in_pitcon1__user__routines(fx_cb_ptr);
        Py_DECREF(fx_cb.args_capi);
    }
    /* End of cleaning variable fx */
    if((PyObject *)capi_fpar_as_array!=fpar_capi) {
        Py_XDECREF(capi_fpar_as_array); }
    }  /* if (capi_fpar_as_array == NULL) ... else of fpar */
    /* End of cleaning variable fpar */
        CFUNCSMESS("Restoring callback variables for `df`.\n");
        df_cb_ptr = swap_active_cb_df_in_pitcon1__user__routines(df_cb_ptr);
        Py_DECREF(df_cb.args_capi);
    }
    /* End of cleaning variable df */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of pitcon1 *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"pitcon1",-1,{{-1}},0,0,(char *)  F_FUNC(pitcon1,PITCON1),  (f2py_init_func)f2py_rout_pitcon_pitcon1,doc_f2py_rout_pitcon_pitcon1},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "pitcon",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_pitcon(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = pitcon_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module pitcon (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'pitcon' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    ierror,iwork,rwork,xr = pitcon1(df,fpar,fx,ipar,iwork,rwork,xr,liw=len(iwork),nvar=len(xr),lrw=len(rwork),imth=1,df_extra_args=(),fx_extra_args=(),overwrite_iwork=0,overwrite_rwork=0,overwrite_xr=0)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    pitcon_error = PyErr_NewException ("pitcon.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_pitcon_error", pitcon_error);
    Py_DECREF(pitcon_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"pitcon");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
