package:
  name: pysces
  version: "0.9.7"

source:
  git_url: https://github.com/PySCeS/pysces.git

build:
  number: 2
  include_recipe: True

requirements:
  build:
    - python
    - setuptools
    - numpy>=1.14
    - libpython
  run:
    - python
    - numpy
    - python-libsbml
    - scipy
    - matplotlib
    - nose

    
about:
  home: http://pysces.sourceforge.net
  license: BSD
  licence_file: LICENSE.txt
  summary: Python Simulator for Cellular Systems

extra:
  maintainers:
   - Brett G. Olivier
