name: CI Anaconda gfortran compiler on Windows

on:
  workflow_dispatch:
  push:
    branches:
      - ci-test

jobs:
  build:
    runs-on: windows-2019
    name: Try Anaconda compilers

    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: false
          python-version: 3.8
          conda-channels: conda-forge

      - name: Prepare conda environment
        run: |
          conda install mamba conda-build conda-verify
          mkdir build_output

      - name: Build packages
        run: mamba build --python 3.8 --numpy 1.17 --no-anaconda-upload --output-folder ./build_output ./packaging/conda

      - uses: actions/upload-artifact@v2
        with:
          name: build_outputs
          path: ./build_output/*/pysces*.tar.bz2
