name: Test conda build

on:
  push:
    branches:
      - ci-test

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
        python-version: [3.8]
    name: Build Anaconda package on $${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda and prepare env
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge
      - run: |
          conda --version
          conda install mamba
          mamba install conda-build conda-verify
          mkdir build_output
      
      - name: Build packages
        run: mamba build --no-anaconda-upload --output-folder ./build_output ./packaging/conda
      
      - uses: actions/upload-artifact@v2
        with:
          name: build_outputs
          path: ./build_output/*
